# Analisando os dados da empresa Olist

## Importando Bibliotecas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [3]:
# Carregando o dataset com informações 
df = pd.read_csv('Olist_Data.csv')
display(df.head(3))

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,124.99,21.88,moveis_escritorio,41.0,1141.0,1.0,8683.0,54.0,64.0,31.0
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,...,289.00,46.48,utilidades_domesticas,43.0,1002.0,3.0,10150.0,89.0,15.0,40.0
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,...,139.94,17.79,moveis_escritorio,55.0,955.0,1.0,8267.0,52.0,52.0,17.0

In [5]:
# Verificando o tamanho do dataset
rows, columns = df.shape
print(f"O dataframe tem {rows} linhas e {columns} colunas.")

O dataframe tem 112650 linhas e 26 colunas.

In [6]:
# Conhecendo as varíaveis e seus tipos.

display(df.dtypes)

customer_id                       object
customer_unique_id                object
customer_zip_code_prefix           int64
customer_city                     object
customer_state                    object
order_id                          object
order_status                      object
order_purchase_timestamp          object
order_approved_at                 object
order_delivered_carrier_date      object
order_delivered_customer_date     object
order_estimated_delivery_date     object
order_item_id                      int64
product_id                        object
seller_id                         object
shipping_limit_date               object
price                            float64
freight_value                    float64
product_category_name             object
product_name_lenght              float64
product_description_lenght       float64
product_photos_qty               float64
product_weight_g                 float64
product_length_cm                float64
product_height_cm                float64
product_width_cm                 float64
dtype: object

In [ ]:
# Colunas relacionadas às dimensões e descrição dos produtos não serão utilizadas;
# O foco da análise está nos aspectos financeiros e logísticos das vendas.
# Métricas de comprimento, peso e quantidade de fotos dos produtos não são relevantes;

# Baseada nessas considerações, serão excluídas as colunas a seguir:
col_drop = [
    'product_name_lenght',
    'product_description_lenght',
    'product_photos_qty',
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm',
    'customer_zip_code_prefix'
]

df = df.drop(columns=col_drop)
df.info()

## Dicionário dos dados

In [9]:
from tabulate import tabulate

data_dictionary = {
    "customer_id": {"type": "object", "description": "Identificador único do cliente no sistema."},
    "customer_unique_id": {"type": "object", "description": "Identificador único global do cliente."},
    "customer_zip_code_prefix": {"type": "int64", "description": "Prefixo do código postal do cliente."},
    "customer_city": {"type": "object", "description": "Cidade do cliente."},
    "customer_state": {"type": "object", "description": "Estado do cliente."},
    "order_id": {"type": "object", "description": "Identificador único do pedido."},
    "order_status": {"type": "object", "description": "Status do pedido (ex: delivered, shipped, etc.)."},
    "order_purchase_timestamp": {"type": "object", "description": "Data e hora da compra do pedido."},
    "order_approved_at": {"type": "object", "description": "Data e hora de aprovação do pedido."},
    "order_delivered_carrier_date": {"type": "object", "description": "Data em que o pedido foi entregue ao transportador."},
    "order_delivered_customer_date": {"type": "object", "description": "Data em que o pedido foi entregue ao cliente."},
    "order_estimated_delivery_date": {"type": "object", "description": "Data estimada para a entrega do pedido."},
    "order_item_id": {"type": "int64", "description": "Identificador do item dentro do pedido."},
    "product_id": {"type": "object", "description": "Identificador único do produto."},
    "seller_id": {"type": "object", "description": "Identificador único do vendedor."},
    "shipping_limit_date": {"type": "object", "description": "Data limite para o envio do pedido."},
    "price": {"type": "float64", "description": "Preço do produto."},
    "freight_value": {"type": "float64", "description": "Valor do frete do pedido."},
    "product_category_name": {"type": "object", "description": "Categoria do produto."}
}

table_data = [["Nome da Coluna", "Tipo de Dados", "Descrição"]]
for col, details in data_dictionary.items():
    table_data.append([col, details["type"], details["description"]])

print(tabulate(table_data, headers="firstrow", tablefmt="grid"))

+-------------------------------+-----------------+-----------------------------------------------------+
| Nome da Coluna                | Tipo de Dados   | Descrição                                           |
+===============================+=================+=====================================================+
| customer_id                   | object          | Identificador único do cliente no sistema.          |
+-------------------------------+-----------------+-----------------------------------------------------+
| customer_unique_id            | object          | Identificador único global do cliente.              |
+-------------------------------+-----------------+-----------------------------------------------------+
| customer_zip_code_prefix      | int64           | Prefixo do código postal do cliente.                |
+-------------------------------+-----------------+-----------------------------------------------------+
| customer_city                 | object          | Cidade do cliente.                                  |
+-------------------------------+-----------------+-----------------------------------------------------+
| customer_state                | object          | Estado do cliente.                                  |
+-------------------------------+-----------------+-----------------------------------------------------+
| order_id                      | object          | Identificador único do pedido.                      |
+-------------------------------+-----------------+-----------------------------------------------------+
| order_status                  | object          | Status do pedido (ex: delivered, shipped, etc.).    |
+-------------------------------+-----------------+-----------------------------------------------------+
| order_purchase_timestamp      | object          | Data e hora da compra do pedido.                    |
+-------------------------------+-----------------+-----------------------------------------------------+
| order_approved_at             | object          | Data e hora de aprovação do pedido.                 |
+-------------------------------+-----------------+-----------------------------------------------------+
| order_delivered_carrier_date  | object          | Data em que o pedido foi entregue ao transportador. |
+-------------------------------+-----------------+-----------------------------------------------------+
| order_delivered_customer_date | object          | Data em que o pedido foi entregue ao cliente.       |
+-------------------------------+-----------------+-----------------------------------------------------+
| order_estimated_delivery_date | object          | Data estimada para a entrega do pedido.             |
+-------------------------------+-----------------+-----------------------------------------------------+
| order_item_id                 | int64           | Identificador do item dentro do pedido.             |
+-------------------------------+-----------------+-----------------------------------------------------+
| product_id                    | object          | Identificador único do produto.                     |
+-------------------------------+-----------------+-----------------------------------------------------+
| seller_id                     | object          | Identificador único do vendedor.                    |
+-------------------------------+-----------------+-----------------------------------------------------+
| shipping_limit_date           | object          | Data limite para o envio do pedido.                 |
+-------------------------------+-----------------+-----------------------------------------------------+
| price                         | float64         | Preço do produto.                                   |
+-------------------------------+-----------------+-----------------------------------------------------+
| freight_value                 | float64         | Valor do frete do pedido.                           |
+-------------------------------+-----------------+-----------------------------------------------------+
| product_category_name         | object          | Categoria do produto.                               |
+-------------------------------+-----------------+-----------------------------------------------------+

In [11]:
# Convertendo os dados de data para tipo datetime

df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
df['order_approved_at'] = pd.to_datetime(df['order_approved_at'])
df['order_delivered_carrier_date'] = pd.to_datetime(df['order_delivered_carrier_date'])
df['order_delivered_customer_date'] = pd.to_datetime(df['order_delivered_customer_date'])
df['order_estimated_delivery_date'] = pd.to_datetime(df['order_estimated_delivery_date'])
df['shipping_limit_date'] = pd.to_datetime(df['shipping_limit_date'])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   customer_id                    112650 non-null  object
 1   customer_unique_id             112650 non-null  object
 2   customer_city                  112650 non-null  object
 3   customer_state                 112650 non-null  object
 4   order_id                       112650 non-null  object
 5   order_status                   112650 non-null  object
 6   order_purchase_timestamp       112650 non-null  datetime64[ns]
 7   order_approved_at              112635 non-null  datetime64[ns]
 8   order_delivered_carrier_date   111456 non-null  datetime64[ns]
 9   order_delivered_customer_date  110196 non-null  datetime64[ns]
 10  order_estimated_delivery_date  112650 non-null  datetime64[ns]
 11  order_item_id                  112650 non-null  int64
 12  product_id                     112650 non-null  object
 13  seller_id                      112650 non-null  object
 14  shipping_limit_date            112650 non-null  datetime64[ns]
 15  price                          112650 non-null  float64
 16  freight_value                  112650 non-null  float64
 17  product_category_name          111047 non-null  object
dtypes: datetime64[ns](6), float64(2), int64(1), object(9)
memory usage: 15.5+ MB

In [12]:
df['order_purchase_timestamp'] = df['order_purchase_timestamp'].dt.date
df['order_approved_at'] = df['order_approved_at'].dt.date
df['order_delivered_carrier_date'] = df['order_delivered_carrier_date'].dt.date
df['order_delivered_customer_date'] = df['order_delivered_customer_date'].dt.date
df['order_estimated_delivery_date'] = df['order_estimated_delivery_date'].dt.date
df['shipping_limit_date'] = df['shipping_limit_date'].dt.date

print(df['order_purchase_timestamp'].unique())

[datetime.date(2017, 5, 16) datetime.date(2018, 1, 12)
 datetime.date(2018, 5, 19) datetime.date(2018, 3, 13)
 datetime.date(2018, 7, 29) datetime.date(2017, 9, 14)
 datetime.date(2018, 2, 19) datetime.date(2017, 11, 16)
 datetime.date(2018, 1, 18) datetime.date(2018, 1, 8)
 datetime.date(2017, 11, 27) datetime.date(2018, 2, 7)
 datetime.date(2017, 9, 9) datetime.date(2018, 3, 7)
 datetime.date(2018, 4, 1) datetime.date(2018, 1, 29)
 datetime.date(2018, 8, 13) datetime.date(2018, 6, 18)
 datetime.date(2017, 5, 11) datetime.date(2017, 11, 1)
 datetime.date(2017, 8, 13) datetime.date(2017, 10, 15)
 datetime.date(2018, 5, 8) datetime.date(2017, 4, 14)
 datetime.date(2018, 5, 16) datetime.date(2018, 2, 9)
 datetime.date(2018, 7, 14) datetime.date(2017, 5, 15)
 datetime.date(2017, 11, 24) datetime.date(2018, 5, 25)
 datetime.date(2017, 9, 12) datetime.date(2017, 11, 26)
 datetime.date(2018, 4, 18) datetime.date(2017, 6, 14)
 datetime.date(2018, 3, 12) datetime.date(2018, 5, 9)
 datetime.date(2017, 10, 13) datetime.date(2017, 8, 10)
 datetime.date(2018, 7, 8) datetime.date(2018, 2, 11)
 datetime.date(2018, 7, 6) datetime.date(2017, 12, 18)
 datetime.date(2018, 1, 31) datetime.date(2017, 10, 9)
 datetime.date(2018, 5, 14) datetime.date(2018, 4, 17)
 datetime.date(2017, 1, 26) datetime.date(2018, 4, 14)
 datetime.date(2018, 5, 22) datetime.date(2018, 5, 11)
 datetime.date(2017, 6, 9) datetime.date(2018, 2, 3)
 datetime.date(2017, 7, 11) datetime.date(2018, 6, 6)
 datetime.date(2018, 3, 29) datetime.date(2018, 3, 27)
 datetime.date(2018, 2, 20) datetime.date(2017, 4, 2)
 datetime.date(2017, 11, 19) datetime.date(2017, 10, 1)
 datetime.date(2017, 12, 5) datetime.date(2017, 9, 11)
 datetime.date(2017, 9, 8) datetime.date(2018, 7, 30)
 datetime.date(2018, 1, 21) datetime.date(2018, 3, 21)
 datetime.date(2017, 12, 28) datetime.date(2017, 9, 26)
 datetime.date(2017, 3, 23) datetime.date(2018, 8, 22)
 datetime.date(2018, 8, 25) datetime.date(2018, 1, 11)
 datetime.date(2018, 3, 24) datetime.date(2017, 5, 22)
 datetime.date(2017, 3, 16) datetime.date(2018, 6, 7)
 datetime.date(2018, 5, 2) datetime.date(2017, 10, 27)
 datetime.date(2018, 3, 26) datetime.date(2018, 3, 22)
 datetime.date(2018, 8, 8) datetime.date(2018, 5, 31)
 datetime.date(2017, 10, 6) datetime.date(2018, 4, 15)
 datetime.date(2018, 6, 24) datetime.date(2018, 4, 30)
 datetime.date(2018, 4, 2) datetime.date(2017, 8, 27)
 datetime.date(2017, 8, 11) datetime.date(2017, 12, 27)
 datetime.date(2017, 12, 15) datetime.date(2017, 3, 28)
 datetime.date(2017, 8, 7) datetime.date(2018, 5, 1)
 datetime.date(2018, 6, 30) datetime.date(2017, 9, 21)
 datetime.date(2017, 7, 16) datetime.date(2017, 5, 29)
 datetime.date(2017, 2, 6) datetime.date(2017, 9, 13)
 datetime.date(2017, 12, 21) datetime.date(2018, 2, 26)
 datetime.date(2018, 6, 3) datetime.date(2017, 5, 21)
 datetime.date(2017, 2, 8) datetime.date(2018, 5, 30)
 datetime.date(2017, 8, 1) datetime.date(2018, 6, 11)
 datetime.date(2018, 6, 1) datetime.date(2018, 4, 16)
 datetime.date(2018, 5, 27) datetime.date(2017, 2, 13)
 datetime.date(2017, 5, 6) datetime.date(2017, 6, 24)
 datetime.date(2017, 9, 5) datetime.date(2017, 9, 1)
 datetime.date(2017, 8, 22) datetime.date(2017, 12, 9)
 datetime.date(2017, 11, 28) datetime.date(2018, 2, 8)
 datetime.date(2017, 9, 27) datetime.date(2018, 4, 10)
 datetime.date(2018, 4, 12) datetime.date(2018, 8, 10)
 datetime.date(2017, 5, 23) datetime.date(2018, 1, 2)
 datetime.date(2018, 8, 23) datetime.date(2018, 7, 31)
 datetime.date(2018, 8, 2) datetime.date(2017, 7, 7)
 datetime.date(2018, 3, 16) datetime.date(2018, 7, 1)
 datetime.date(2018, 5, 15) datetime.date(2018, 1, 13)
 datetime.date(2017, 3, 10) datetime.date(2017, 11, 9)
 datetime.date(2017, 2, 9) datetime.date(2018, 8, 14)
 datetime.date(2018, 4, 27) datetime.date(2017, 9, 16)
 datetime.date(2017, 7, 15) datetime.date(2017, 11, 11)
 datetime.date(2017, 8, 8) datetime.date(2018, 4, 20)
 datetime.date(2018, 6, 9) datetime.date(2018, 1, 6)
 datetime.date(2018, 8, 4) datetime.date(2018, 4, 8)
 datetime.date(2018, 7, 24) datetime.date(2018, 2, 15)
 datetime.date(2017, 5, 30) datetime.date(2018, 6, 4)
 datetime.date(2017, 3, 21) datetime.date(2018, 8, 17)
 datetime.date(2017, 12, 12) datetime.date(2018, 7, 4)
 datetime.date(2018, 5, 29) datetime.date(2018, 8, 6)
 datetime.date(2017, 12, 2) datetime.date(2017, 3, 4)
 datetime.date(2017, 10, 11) datetime.date(2017, 1, 31)
 datetime.date(2018, 2, 14) datetime.date(2017, 9, 25)
 datetime.date(2018, 8, 1) datetime.date(2018, 2, 27)
 datetime.date(2018, 3, 20) datetime.date(2017, 4, 4)
 datetime.date(2017, 3, 13) datetime.date(2018, 1, 10)
 datetime.date(2017, 2, 22) datetime.date(2018, 4, 9)
 datetime.date(2017, 12, 6) datetime.date(2018, 8, 21)
 datetime.date(2017, 12, 11) datetime.date(2017, 11, 25)
 datetime.date(2018, 3, 23) datetime.date(2018, 2, 6)
 datetime.date(2017, 11, 8) datetime.date(2018, 2, 1)
 datetime.date(2018, 3, 6) datetime.date(2018, 1, 23)
 datetime.date(2018, 1, 19) datetime.date(2018, 1, 16)
 datetime.date(2018, 4, 25) datetime.date(2017, 4, 30)
 datetime.date(2017, 8, 15) datetime.date(2018, 6, 22)
 datetime.date(2017, 10, 4) datetime.date(2017, 5, 19)
 datetime.date(2018, 5, 6) datetime.date(2017, 12, 4)
 datetime.date(2018, 6, 17) datetime.date(2017, 7, 1)
 datetime.date(2018, 4, 26) datetime.date(2017, 4, 25)
 datetime.date(2017, 3, 20) datetime.date(2017, 6, 22)
 datetime.date(2017, 8, 31) datetime.date(2018, 5, 3)
 datetime.date(2018, 8, 19) datetime.date(2018, 7, 18)
 datetime.date(2017, 6, 26) datetime.date(2017, 7, 9)
 datetime.date(2017, 11, 7) datetime.date(2017, 9, 7)
 datetime.date(2017, 8, 19) datetime.date(2018, 3, 15)
 datetime.date(2017, 10, 16) datetime.date(2017, 5, 24)
 datetime.date(2018, 7, 9) datetime.date(2017, 9, 15)
 datetime.date(2018, 2, 16) datetime.date(2017, 6, 20)
 datetime.date(2017, 8, 30) datetime.date(2018, 6, 27)
 datetime.date(2017, 6, 23) datetime.date(2017, 8, 23)
 datetime.date(2018, 6, 28) datetime.date(2017, 3, 6)
 datetime.date(2018, 7, 5) datetime.date(2018, 1, 27)
 datetime.date(2018, 8, 3) datetime.date(2018, 8, 5)
 datetime.date(2018, 6, 21) datetime.date(2017, 10, 24)
 datetime.date(2018, 8, 7) datetime.date(2018, 5, 24)
 datetime.date(2018, 2, 5) datetime.date(2018, 3, 18)
 datetime.date(2017, 10, 19) datetime.date(2017, 5, 3)
 datetime.date(2017, 7, 21) datetime.date(2017, 8, 18)
 datetime.date(2018, 1, 22) datetime.date(2018, 2, 13)
 datetime.date(2016, 10, 10) datetime.date(2017, 9, 17)
 datetime.date(2017, 12, 17) datetime.date(2017, 8, 5)
 datetime.date(2018, 8, 11) datetime.date(2018, 3, 2)
 datetime.date(2017, 5, 18) datetime.date(2017, 9, 23)
 datetime.date(2017, 1, 29) datetime.date(2018, 2, 12)
 datetime.date(2018, 1, 4) datetime.date(2018, 7, 19)
 datetime.date(2018, 6, 16) datetime.date(2017, 10, 30)
 datetime.date(2017, 3, 26) datetime.date(2018, 1, 30)
 datetime.date(2017, 6, 19) datetime.date(2017, 7, 27)
 datetime.date(2017, 4, 21) datetime.date(2017, 11, 18)
 datetime.date(2017, 7, 29) datetime.date(2018, 4, 24)
 datetime.date(2017, 9, 18) datetime.date(2018, 5, 12)
 datetime.date(2018, 1, 17) datetime.date(2018, 6, 12)
 datetime.date(2018, 6, 25) datetime.date(2017, 3, 11)
 datetime.date(2017, 11, 23) datetime.date(2017, 5, 5)
 datetime.date(2018, 5, 18) datetime.date(2018, 4, 3)
 datetime.date(2018, 6, 13) datetime.date(2017, 7, 28)
 datetime.date(2017, 10, 28) datetime.date(2017, 6, 8)
 datetime.date(2017, 6, 27) datetime.date(2017, 2, 3)
 datetime.date(2018, 5, 17) datetime.date(2017, 3, 1)
 datetime.date(2018, 3, 14) datetime.date(2017, 10, 25)
 datetime.date(2017, 6, 13) datetime.date(2017, 6, 15)
 datetime.date(2017, 3, 22) datetime.date(2018, 4, 19)
 datetime.date(2017, 6, 10) datetime.date(2018, 6, 20)
 datetime.date(2017, 5, 9) datetime.date(2018, 7, 15)
 datetime.date(2018, 2, 28) datetime.date(2017, 11, 14)
 datetime.date(2017, 4, 20) datetime.date(2018, 5, 10)
 datetime.date(2017, 4, 11) datetime.date(2017, 12, 10)
 datetime.date(2018, 2, 2) datetime.date(2018, 8, 28)
 datetime.date(2018, 7, 3) datetime.date(2018, 8, 26)
 datetime.date(2018, 1, 26) datetime.date(2018, 2, 21)
 datetime.date(2017, 2, 1) datetime.date(2017, 11, 30)
 datetime.date(2018, 2, 23) datetime.date(2017, 12, 29)
 datetime.date(2017, 6, 30) datetime.date(2018, 8, 29)
 datetime.date(2018, 6, 14) datetime.date(2017, 4, 1)
 datetime.date(2017, 7, 12) datetime.date(2018, 3, 25)
 datetime.date(2017, 9, 6) datetime.date(2018, 7, 16)
 datetime.date(2018, 8, 27) datetime.date(2018, 3, 4)
 datetime.date(2017, 6, 25) datetime.date(2018, 5, 13)
 datetime.date(2017, 8, 2) datetime.date(2017, 4, 27)
 datetime.date(2017, 7, 18) datetime.date(2018, 2, 4)
 datetime.date(2018, 1, 25) datetime.date(2017, 5, 1)
 datetime.date(2018, 4, 4) datetime.date(2017, 11, 22)
 datetime.date(2017, 7, 30) datetime.date(2018, 7, 21)
 datetime.date(2017, 10, 17) datetime.date(2018, 7, 13)
 datetime.date(2017, 6, 12) datetime.date(2018, 3, 30)
 datetime.date(2017, 4, 8) datetime.date(2017, 7, 31)
 datetime.date(2017, 11, 2) datetime.date(2018, 4, 23)
 datetime.date(2018, 7, 27) datetime.date(2018, 7, 20)
 datetime.date(2017, 7, 8) datetime.date(2018, 1, 24)
 datetime.date(2017, 4, 5) datetime.date(2017, 11, 15)
 datetime.date(2018, 1, 3) datetime.date(2017, 10, 26)
 datetime.date(2017, 5, 2) datetime.date(2018, 3, 19)
 datetime.date(2018, 7, 22) datetime.date(2018, 6, 29)
 datetime.date(2018, 1, 14) datetime.date(2017, 4, 18)
 datetime.date(2017, 3, 27) datetime.date(2017, 8, 3)
 datetime.date(2018, 2, 24) datetime.date(2018, 8, 12)
 datetime.date(2017, 7, 4) datetime.date(2018, 5, 26)
 datetime.date(2017, 8, 6) datetime.date(2018, 7, 23)
 datetime.date(2018, 8, 15) datetime.date(2017, 7, 24)
 datetime.date(2017, 8, 17) datetime.date(2017, 7, 19)
 datetime.date(2018, 6, 15) datetime.date(2017, 7, 2)
 datetime.date(2017, 7, 13) datetime.date(2017, 8, 28)
 datetime.date(2017, 8, 20) datetime.date(2017, 12, 16)
 datetime.date(2018, 8, 9) datetime.date(2017, 3, 14)
 datetime.date(2017, 7, 3) datetime.date(2017, 4, 7)
 datetime.date(2018, 4, 21) datetime.date(2018, 1, 9)
 datetime.date(2017, 3, 17) datetime.date(2018, 7, 28)
 datetime.date(2018, 7, 25) datetime.date(2017, 7, 20)
 datetime.date(2017, 12, 24) datetime.date(2017, 3, 18)
 datetime.date(2017, 3, 7) datetime.date(2017, 3, 30)
 datetime.date(2018, 5, 21) datetime.date(2018, 3, 5)
 datetime.date(2017, 6, 2) datetime.date(2018, 8, 20)
 datetime.date(2017, 8, 16) datetime.date(2018, 5, 20)
 datetime.date(2017, 1, 25) datetime.date(2017, 12, 3)
 datetime.date(2017, 12, 25) datetime.date(2018, 1, 15)
 datetime.date(2018, 3, 17) datetime.date(2017, 8, 24)
 datetime.date(2017, 2, 17) datetime.date(2016, 10, 6)
 datetime.date(2017, 10, 23) datetime.date(2017, 10, 12)
 datetime.date(2017, 9, 3) datetime.date(2017, 12, 13)
 datetime.date(2018, 4, 13) datetime.date(2017, 12, 23)
 datetime.date(2017, 3, 8) datetime.date(2017, 5, 31)
 datetime.date(2017, 7, 23) datetime.date(2017, 8, 25)
 datetime.date(2018, 4, 11) datetime.date(2017, 11, 10)
 datetime.date(2017, 10, 22) datetime.date(2017, 5, 10)
 datetime.date(2018, 6, 5) datetime.date(2018, 7, 11)
 datetime.date(2018, 3, 3) datetime.date(2017, 9, 4)
 datetime.date(2017, 7, 10) datetime.date(2017, 5, 4)
 datetime.date(2018, 6, 2) datetime.date(2018, 3, 31)
 datetime.date(2017, 2, 7) datetime.date(2017, 3, 31)
 datetime.date(2017, 6, 18) datetime.date(2017, 8, 4)
 datetime.date(2017, 6, 28) datetime.date(2018, 4, 22)
 datetime.date(2018, 6, 8) datetime.date(2018, 3, 11)
 datetime.date(2017, 12, 26) datetime.date(2017, 5, 12)
 datetime.date(2018, 2, 17) datetime.date(2018, 1, 5)
 datetime.date(2017, 6, 17) datetime.date(2017, 8, 21)
 datetime.date(2018, 1, 7) datetime.date(2018, 7, 2)
 datetime.date(2017, 9, 24) datetime.date(2018, 5, 7)
 datetime.date(2017, 6, 21) datetime.date(2017, 4, 29)
 datetime.date(2017, 4, 13) datetime.date(2017, 12, 31)
 datetime.date(2018, 4, 6) datetime.date(2017, 11, 13)
 datetime.date(2018, 3, 1) datetime.date(2016, 10, 7)
 datetime.date(2017, 10, 2) datetime.date(2017, 6, 11)
 datetime.date(2017, 12, 22) datetime.date(2017, 12, 8)
 datetime.date(2018, 4, 5) datetime.date(2017, 12, 14)
 datetime.date(2017, 6, 7) datetime.date(2017, 5, 17)
 datetime.date(2018, 2, 25) datetime.date(2018, 4, 7)
 datetime.date(2017, 7, 25) datetime.date(2018, 3, 9)
 datetime.date(2018, 1, 1) datetime.date(2017, 5, 28)
 datetime.date(2017, 1, 23) datetime.date(2017, 4, 10)
 datetime.date(2017, 8, 29) datetime.date(2017, 10, 20)
 datetime.date(2018, 6, 23) datetime.date(2018, 1, 28)
 datetime.date(2017, 11, 21) datetime.date(2017, 11, 20)
 datetime.date(2017, 11, 17) datetime.date(2018, 2, 22)
 datetime.date(2018, 3, 8) datetime.date(2017, 1, 19)
 datetime.date(2017, 5, 8) datetime.date(2017, 10, 14)
 datetime.date(2017, 7, 5) datetime.date(2017, 10, 10)
 datetime.date(2017, 7, 26) datetime.date(2018, 7, 12)
 datetime.date(2017, 11, 29) datetime.date(2017, 2, 2)
 datetime.date(2017, 10, 29) datetime.date(2018, 5, 4)
 datetime.date(2018, 4, 28) datetime.date(2017, 2, 15)
 datetime.date(2017, 11, 4) datetime.date(2017, 8, 26)
 datetime.date(2017, 9, 20) datetime.date(2017, 2, 20)
 datetime.date(2017, 3, 3) datetime.date(2018, 7, 26)
 datetime.date(2017, 8, 12) datetime.date(2018, 6, 19)
 datetime.date(2017, 5, 14) datetime.date(2017, 4, 12)
 datetime.date(2018, 6, 10) datetime.date(2018, 2, 18)
 datetime.date(2017, 5, 20) datetime.date(2017, 9, 19)
 datetime.date(2017, 10, 18) datetime.date(2017, 7, 6)
 datetime.date(2017, 5, 26) datetime.date(2018, 5, 5)
 datetime.date(2017, 12, 1) datetime.date(2018, 7, 10)
 datetime.date(2017, 2, 4) datetime.date(2018, 6, 26)
 datetime.date(2017, 11, 6) datetime.date(2017, 1, 13)
 datetime.date(2017, 2, 26) datetime.date(2017, 4, 22)
 datetime.date(2017, 4, 3) datetime.date(2017, 12, 7)
 datetime.date(2017, 8, 14) datetime.date(2018, 8, 18)
 datetime.date(2017, 11, 5) datetime.date(2017, 4, 26)
 datetime.date(2017, 10, 8) datetime.date(2017, 3, 12)
 datetime.date(2017, 6, 1) datetime.date(2017, 3, 15)
 datetime.date(2017, 4, 9) datetime.date(2017, 1, 18)
 datetime.date(2017, 7, 14) datetime.date(2017, 6, 5)
 datetime.date(2018, 8, 16) datetime.date(2017, 4, 24)
 datetime.date(2017, 2, 24) datetime.date(2017, 9, 29)
 datetime.date(2017, 5, 7) datetime.date(2017, 4, 23)
 datetime.date(2017, 2, 16) datetime.date(2017, 7, 17)
 datetime.date(2017, 3, 19) datetime.date(2018, 3, 10)
 datetime.date(2017, 9, 22) datetime.date(2017, 2, 5)
 datetime.date(2017, 12, 20) datetime.date(2017, 4, 16)
 datetime.date(2017, 5, 13) datetime.date(2017, 5, 25)
 datetime.date(2017, 6, 16) datetime.date(2018, 2, 10)
 datetime.date(2018, 7, 17) datetime.date(2018, 4, 29)
 datetime.date(2017, 10, 31) datetime.date(2017, 1, 30)
 datetime.date(2018, 1, 20) datetime.date(2016, 10, 5)
 datetime.date(2017, 10, 5) datetime.date(2017, 3, 5)
 datetime.date(2017, 1, 5) datetime.date(2017, 3, 9)
 datetime.date(2017, 6, 29) datetime.date(2017, 11, 12)
 datetime.date(2017, 2, 27) datetime.date(2017, 6, 3)
 datetime.date(2017, 4, 17) datetime.date(2018, 3, 28)
 datetime.date(2017, 8, 9) datetime.date(2017, 2, 18)
 datetime.date(2018, 5, 23) datetime.date(2018, 8, 24)
 datetime.date(2017, 9, 28) datetime.date(2017, 10, 7)
 datetime.date(2018, 7, 7) datetime.date(2016, 10, 8)
 datetime.date(2017, 4, 15) datetime.date(2017, 7, 22)
 datetime.date(2017, 6, 6) datetime.date(2017, 3, 25)
 datetime.date(2017, 9, 2) datetime.date(2017, 4, 28)
 datetime.date(2017, 11, 3) datetime.date(2017, 12, 19)
 datetime.date(2017, 2, 11) datetime.date(2017, 1, 20)
 datetime.date(2017, 10, 21) datetime.date(2017, 9, 30)
 datetime.date(2017, 2, 28) datetime.date(2017, 1, 27)
 datetime.date(2018, 5, 28) datetime.date(2017, 10, 3)
 datetime.date(2017, 1, 22) datetime.date(2017, 4, 6)
 datetime.date(2017, 12, 30) datetime.date(2017, 2, 10)
 datetime.date(2017, 4, 19) datetime.date(2017, 2, 14)
 datetime.date(2017, 3, 29) datetime.date(2017, 6, 4)
 datetime.date(2017, 3, 24) datetime.date(2017, 9, 10)
 datetime.date(2017, 2, 12) datetime.date(2017, 5, 27)
 datetime.date(2017, 1, 24) datetime.date(2017, 2, 19)
 datetime.date(2017, 1, 15) datetime.date(2016, 10, 4)
 datetime.date(2017, 1, 12) datetime.date(2017, 1, 16)
 datetime.date(2017, 2, 25) datetime.date(2017, 3, 2)
 datetime.date(2017, 1, 14) datetime.date(2017, 1, 28)
 datetime.date(2016, 10, 3) datetime.date(2017, 1, 17)
 datetime.date(2017, 2, 21) datetime.date(2017, 1, 11)
 datetime.date(2017, 2, 23) datetime.date(2016, 10, 9)
 datetime.date(2017, 1, 9) datetime.date(2017, 1, 21)
 datetime.date(2017, 1, 8) datetime.date(2016, 9, 15)
 datetime.date(2017, 1, 7) datetime.date(2016, 12, 23)
 datetime.date(2017, 1, 10) datetime.date(2017, 1, 6)
 datetime.date(2018, 9, 3) datetime.date(2016, 9, 5)
 datetime.date(2016, 9, 4) datetime.date(2016, 10, 2)]

In [13]:
df['order_delivered_carrier_date'] = pd.to_datetime(df['order_delivered_carrier_date'])
df['order_delivered_customer_date'] = pd.to_datetime(df['order_delivered_customer_date'])

df['days_delivery_diff'] = (df['order_delivered_customer_date'] - df['order_delivered_carrier_date']).dt.days

print(df[['order_delivered_carrier_date', 'order_delivered_customer_date', 'days_delivery_diff']])

       order_delivered_carrier_date order_delivered_customer_date  \
0                        2017-05-23                    2017-05-25
1                        2018-01-15                    2018-01-29
2                        2018-06-11                    2018-06-14
3                        2018-03-27                    2018-03-28
4                        2018-07-30                    2018-08-09
...                             ...                           ...
112645                   2018-04-11                    2018-04-13
112646                   2018-04-05                    2018-04-11
112647                   2018-04-09                    2018-05-09
112648                   2017-11-06                    2017-11-16
112649                   2017-12-21                    2017-12-26

        days_delivery_diff
0                      2.0
1                     14.0
2                      3.0
3                      1.0
4                     10.0
...                    ...
112645                 2.0
112646                 6.0
112647                30.0
112648                10.0
112649                 5.0

[112650 rows x 3 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 19 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   customer_id                    112650 non-null  object
 1   customer_unique_id             112650 non-null  object
 2   customer_city                  112650 non-null  object
 3   customer_state                 112650 non-null  object
 4   order_id                       112650 non-null  object
 5   order_status                   112650 non-null  object
 6   order_purchase_timestamp       112650 non-null  object
 7   order_approved_at              112635 non-null  object
 8   order_delivered_carrier_date   111456 non-null  datetime64[ns]
 9   order_delivered_customer_date  110196 non-null  datetime64[ns]
 10  order_estimated_delivery_date  112650 non-null  object
 11  order_item_id                  112650 non-null  int64
 12  product_id                     112650 non-null  object
 13  seller_id                      112650 non-null  object
 14  shipping_limit_date            112650 non-null  object
 15  price                          112650 non-null  float64
 16  freight_value                  112650 non-null  float64
 17  product_category_name          111047 non-null  object
 18  days_delivery_diff             110195 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(1), object(13)
memory usage: 16.3+ MB

## Criando novas colunas para análise

In [16]:
# Coluna valor total do pedido (preço + frete)

df['total_order_value'] = df['price'] + df['freight_value']
display(df['total_order_value'])

0         146.87
1         335.48
2         157.73
3         173.30
4         252.25
           ...
112645     88.78
112646    129.06
112647     56.04
112648    711.07
112649     21.77
Name: total_order_value, Length: 112650, dtype: float64

In [18]:

df['order_approved_at'] = pd.to_datetime(df['order_approved_at'])
df['order_delivered_customer_date'] = pd.to_datetime(df['order_delivered_customer_date'])

df['processing_time_days'] = (df['order_delivered_customer_date'] - df['order_approved_at']).dt.days

display(df[['order_approved_at', 'order_delivered_customer_date', 'processing_time_days']])

       order_approved_at order_delivered_customer_date  processing_time_days
0             2017-05-16                    2017-05-25                   9.0
1             2018-01-12                    2018-01-29                  17.0
2             2018-05-20                    2018-06-14                  25.0
3             2018-03-13                    2018-03-28                  15.0
4             2018-07-29                    2018-08-09                  11.0
...                  ...                           ...                   ...
112645        2018-04-07                    2018-04-13                   6.0
112646        2018-04-04                    2018-04-11                   7.0
112647        2018-04-08                    2018-05-09                  31.0
112648        2017-11-03                    2017-11-16                  13.0
112649        2017-12-19                    2017-12-26                   7.0

[112650 rows x 3 columns]

In [20]:
# Número de itens por pedido

df['num_items_per_order'] = df.groupby('order_id')['order_item_id'].transform('count')
display(df['num_items_per_order'])

0         1
1         1
2         1
3         1
4         1
         ..
112645    1
112646    1
112647    1
112648    1
112649    1
Name: num_items_per_order, Length: 112650, dtype: int64

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 22 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   customer_id                    112650 non-null  object
 1   customer_unique_id             112650 non-null  object
 2   customer_city                  112650 non-null  object
 3   customer_state                 112650 non-null  object
 4   order_id                       112650 non-null  object
 5   order_status                   112650 non-null  object
 6   order_purchase_timestamp       112650 non-null  object
 7   order_approved_at              112635 non-null  datetime64[ns]
 8   order_delivered_carrier_date   111456 non-null  datetime64[ns]
 9   order_delivered_customer_date  110196 non-null  datetime64[ns]
 10  order_estimated_delivery_date  112650 non-null  object
 11  order_item_id                  112650 non-null  int64
 12  product_id                     112650 non-null  object
 13  seller_id                      112650 non-null  object
 14  shipping_limit_date            112650 non-null  object
 15  price                          112650 non-null  float64
 16  freight_value                  112650 non-null  float64
 17  product_category_name          111047 non-null  object
 18  days_delivery_diff             110195 non-null  float64
 19  total_order_value              112650 non-null  float64
 20  processing_time_days           110181 non-null  float64
 21  num_items_per_order            112650 non-null  int64
dtypes: datetime64[ns](3), float64(5), int64(2), object(12)
memory usage: 18.9+ MB

In [23]:
df.to_csv("Olist_final.csv", index = False)
print("Arquivo CSV 'Olist_final' salvo com sucesso.")

Arquivo CSV 'Olist_final' salvo com sucesso.

O link para a visualização das análises se encontra [aqui](https://public.tableau.com/authoring/Entrega_Aula15/Sheet1/Dashboard#1)!